services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SchamsNet\T3extensionsWidget\:
    resource: '../Classes/*'

  cache.ListExtensionsWidget:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['t3extensions_widget']

  dashboard.widget.SchamsNet.T3extensionsWidget.LastNewExtensionsWidget:
    class: 'SchamsNet\T3extensionsWidget\Widgets\ListExtensionsWidget'
    arguments:
      $cache: '@cache.ListExtensionsWidget'
      $options:
        title: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastNewExtensions.title'
        feedUrl: 'https://t3extensions.org/api/last10/new'
    tags:
      - name: dashboard.widget
        identifier: 'LastNewExtensionsWidget'
        groupNames: 'typo3'
        title: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastNewExtensions.title'
        description: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastNewExtensions.description'
        iconIdentifier: 'content-widget-text'
        height: 'large'
        width: 'small'

  dashboard.widget.SchamsNet.T3extensionsWidget.LastUpdatedExtensionsWidget:
    class: 'SchamsNet\T3extensionsWidget\Widgets\ListExtensionsWidget'
    arguments:
      $cache: '@cache.ListExtensionsWidget'
      $options:
        title: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastUpdatedExtensions.title'
        feedUrl: 'https://t3extensions.org/api/last10/updates'
    tags:
      - name: dashboard.widget
        identifier: 'LastUpdatedExtensionsWidget'
        groupNames: 'typo3'
        title: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastUpdatedExtensions.title'
        description: 'LLL:EXT:t3extensions_widget/Resources/Private/Language/locallang.xlf:widgets.lastUpdatedExtensions.description'
        iconIdentifier: 'content-widget-text'
        height: 'large'
        width: 'small'
